# fly.toml app configuration file generated for shift-app on 2024-02-01T19:27:59+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shift-app'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '16'
    PHP_VERSION = '7.4'

[env]
  APP_ENV = 'production'
  DB_CONNECTION= 'pgsql'
  DB_HOST= 'aws-0-ap-northeast-1.pooler.supabase.com'
  DB_PORT= '5432'
  DB_DATABASE= 'postgres'
  DB_USERNAME= 'postgres.gospzfmoogeiuzunrtww'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
